version: '3.2'
services:
  app:
    build: .
    container_name: refatorar
    volumes:
      - .:/var/www
    depends_on:
      - db
    links:
      - db
    ports:
      - 8000:80
    networks:
      - default
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: aulas
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - default
networks:
  default:
    driver: bridge
